name: Check PR
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  checks:
    uses: sendsay-ru/.github/.github/workflows/lint.yml@stable
    with:
      config-path: .github/lint.json
      install-command: yarn
      node-version: 18
    secrets: inherit
