name: Lint
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . < ${{ inputs.config-path }})" >> $GITHUB_OUTPUT

  checks:
    runs-on: ubuntu-latest
    needs: config
    strategy:
      matrix: ${{ fromJson(needs.config.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages
        shell: bash
        run: yarn install
      - name: ${{ matrix.script }}
        run: ${{ matrix.script }}
